project/appname1/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    #url(r'^$',views.index),
    url(r'^login/$',views.login),
    url(r'^register/$',views.register),
    url(r'^register_handle/$',views.register_handle),
    url(r'^login_handle/$',views.login_handle),
    url(r'^user_center_info/$',views.user_center_info),
    url(r'^user_center_site/$',views.user_center_site),
    url(r'^user_center_order/$',views.user_center_order),
    url(r'^userinfo_handle/$',views.userinfo_handle),
    url(r'^exit/$',views.exit),
    url(r'^islogin/$',views.isLogin),
]

project/project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('appname2.urls')),
    url(r'^', include('appname1.urls')),
    url(r'^', include('appname3.urls')),
    url(r'^', include('appname4.urls')),
]

project/appname1/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):
    username = models.CharField(max_length=20)
    upassword = models.CharField(max_length=40)
    uemail = models.CharField(max_length=20)
    uaddress = models.CharField(max_length=100,null=True)
    ureceive = models.CharField(max_length=10,null=True)
    ucode = models.CharField(max_length=6,null=True)
    uphone = models.CharField(max_length=11,null=True)

project/appname4/models.py
from django.db import models
from appname1.models import UserInfo
from appname2.models import GoodsInfo
# Create your models here.
class orderMain(models.Model):
    order_id = models.CharField(max_length=20,primary_key=True)
    user = models.ForeignKey(UserInfo)
    order_date = models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=8,decimal_places=2,default=0)
    state = models.IntegerField(default=0)

class orderDetail(models.Model):
    main = models.ForeignKey(orderMain)
    goods = models.ForeignKey(GoodsInfo)
    price = models.DecimalField(max_digits=8,decimal_places=2)
    count = models.IntegerField()

project/appname1/views.py
#coding=utf-8
from django.http import JsonResponse
from django.shortcuts import render,redirect
from hashlib import sha1
from models import *
from Is_Login import isLogin
from appname2.models import GoodsInfo
from appname4.models import orderMain,orderDetail
from django.core.paginator import Paginator

# Create your views here.
def login(request):
    name = request.COOKIES.get('username','')
    content = {'title':'登录','username':name,'top':'0'}
    return render(request,'appname1/login.html',content)

def login_handle(request):
    username = request.POST.get('username')
    password = request.POST.get('pwd')
    jizhu = request.POST.get('jizhu')

    user = UserInfo.objects.filter(username=username)
    s1 = sha1()
    s1.update(password)
    sha1_pwd = s1.hexdigest()
    if user.count() == 1:
        if user[0].upassword == sha1_pwd:
            request.session['uid'] = user[0].id
            request.session['uname'] = user[0].username
            path = request.session.get('urlpath','/')
            print path
            response = redirect(path)
            if jizhu == '1':
                response.set_cookie('username',username)
            else:
                response.set_cookie('username','',max_age=-1)
            return response
        else:
            return render(request,'appname1/login.html',{'pwd_error':'1'})
    else:
        return render(request,'appname1/login.html',{'name_error':'1'})



def register(request):
    content = {'title': '注册','top':'0'}
    return render(request,'appname1/register.html',content)

def register_handle(request):
    if request.method == 'POST':
        req=request.POST
        user_name = req.get('user_name')
        pwd = req.get('pwd')
        email = req.get('email')
        s1 = sha1()
        s1.update(pwd)
        spwd = s1.hexdigest()
        user = UserInfo()
        user.username = user_name
        user.upassword = spwd
        user.uemail = email
        user.save()
        return redirect('/login/')
    elif request.method == 'GET':
        req = request.GET
        user_name = req.get('user_name')
        user = UserInfo.objects.filter(username=user_name)
        if user.count() == 1:
            return JsonResponse({'exist':'1'})
        else:
            return JsonResponse({'exist':'0'})

'''
def index(request):
    content = {'title':'首页','top':'1'}
    return render(request,'appname2/index.html',content)
'''
@isLogin
def user_center_info(request):
    user = UserInfo.objects.get(id=request.session['uid'])
    recentlystr = request.COOKIES.get('recently','')
    list = []
    recentlylist = recentlystr.split(',')
    recentlylist.pop()
    for i in recentlylist:
        good = GoodsInfo.objects.get(id=i)
        list.append(good)
    return render(request,'appname1/user_center_info.html',{'user':user,'title':'用户中心','top':'1','list':list})
@isLogin
def user_center_site(request):
    user = UserInfo.objects.get(id=request.session['uid'])
    return render(request,'appname1/user_center_site.html',{'user': user,'title':'收货地址','top':'1'})
@isLogin
def user_center_order(request):
    index = request.GET.get('index',1)
    print index
    order = orderMain.objects.filter(user_id=request.session['uid']).order_by('-order_date')
    paginator = Paginator(order,5)
    page = paginator.page(index)
    pagenum = []
    if page.paginator.num_pages<5:
        pagenum = range(1,page.paginator.num_pages+1)
    elif page.number <=2:
        pagenum = range(1,6)
    elif page.number>=page.paginator.num_pages-1:
        pagenum = range(page.paginator.num_pages-4,page.paginator.num_pages+1)
    else:
        pagenum = range(page.number-2,page.number+3)

    return render(request,'appname1/user_center_order.html',{'title':'全部订单','top':'1','page':page,'pagenum':pagenum})
@isLogin
def userinfo_handle(request):
    post = request.POST
    user = UserInfo.objects.get(id=request.session['uid'])
    user.ureceive = post.get('ureceive')
    user.uaddress = post.get('address')
    user.ucode = post.get('code')
    user.uphone = post.get('phone')
    user.save()
    return render(request, 'appname1/user_center_site.html', {'user': user,'top':'1'})

def exit(request):
    request.session.flush()
    return redirect('/')

def isLogin(reuqest):
    if reuqest.session.has_key('uid'):
        return JsonResponse({'islogin':'1'})
    else:
        return JsonResponse({'islogin':'0'})

project/templates/appname1/base_temp.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{{title}}</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	{%if car_show == '1'%}

	{%endif%}
    {%block head%}
    {%endblock head%}
</head>
<body>
{%if top|default:'1' == '1'%}
<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{%if request.session.uid%}
				<div class="login_btn fl">
					欢迎您：<em>{{request.session.uname}}</em>
					<span>|</span>
					<a href="/exit/">退出</a>
				</div>
				{%else%}
				<div class="login_btn fl">
					<a href="/login/">登录</a>
					<span>|</span>
					<a href="/register/">注册</a>
				</div>
				{%endif%}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user_center_info/">用户中心</a>
					<span>|</span>
					<a href="/cart/">我的购物车</a>
					<span>|</span>
					<a href="/user_center_order/">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{%endif%}

{%block user%}
	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{{title}}</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{%endblock user%}
{%if car_show == '1'%}
<div class="search_bar clearfix">
    <a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
    <div class="search_con fl">
		<form action="/search/" method="get">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
        	<input type="submit" class="input_btn fr" name="" value="搜索">
		</form>

    </div>
    <div class="guest_cart fr">
        <a href="/cart/" class="cart_name fl">我的购物车</a>
        <div class="goods_count fl" id="show_count">1</div>
    </div>
</div>
<script>
		function refresh() {
				$.get('/islogin/',function (data) {
				if(data.islogin == '1'){
					$.get('/count/',function (data) {
						$('#show_count').text(data.count);
					})
				}else {
					$('#show_count').text(0);
				}
			})
			}
		$(function () {
			refresh();
		})
</script>
{%endif%}

{%block content%}
{%endblock content%}
    <div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

</body>
</html>

project/templates/appname1/login.html
{%extends 'appname1/base_temp.html'%}
{%block head%}
<script type="text/javascript" src="/static/js/jquery.cookie.js"></script>
<script>
	$(function () {
	    var nameok = false;
		var passok = false;
	    $('.name_input').blur(function () {
	        var userinput = $('.name_input');
			if(userinput.val().length<6 || userinput.val().length>20){
	            userinput.next().html('请输入6-20位用户名').show();
	            nameok = false;
			}else{
			    userinput.next().hide();
			    nameok = true
			}
        });
	    $('.pass_input').blur(function () {
			var passinput = $('.pass_input');
			if(passinput.val().length<8 || passinput.val().length>20){
			    passinput.next().html('密码为8-20位').show();
			    passok = false;
			}else {
			    passinput.next().hide();
			    passok = true;
			}
        });

	    $('#login').submit(function () {
			$('.name_input').blur();
	        $('.pass_input').blur();
	        return nameok && passok;
        });

		if('{{name_error}}' == '1'){
		    $('.name_input').next().html('用户名不存在').show()
		}
		if('{{pwd_error}}' == '1'){
		    $('.pass_input').next().html('密码错误').show()
		}
    })
</script>
{%endblock head%}
{%block user%}
{%endblock user%}
{%block content%}


	<div class="login_top clearfix">
		<a href="../appname2/index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" action="/login_handle/" id="login">
						{%csrf_token%}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{username}}">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码" value="">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="jizhu" value="1">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{%endblock content%}



project/templates/appname1/register.html
{%extends 'appname1/base_temp.html'%}
{%block head%}
<script type="text/javascript" src="/static/js/register.js"></script>
{%endblock head%}
{%block content%}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="/register_handle/" id="reg_form">
					{%csrf_token%}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{%endblock content%}

project/templates/appname1/user_center_info.html
{%extends 'appname1/base_temp.html'%}
{%block user%}
{{block.super}}
{%endblock user%}
{%block content%}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user_center_info/" class="active">· 个人信息</a></li>
				<li><a href="/user_center_order/">· 全部订单</a></li>
				<li><a href="/user_center_site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{user.username|default:''}}</li>
							<li><span>联系方式：</span>{{user.uphone|default:'无'}}</li>
							<li><span>联系地址：</span>{{user.uaddress|default:'无'}}</li>
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
					{%for good in list%}
						<li>
						<a href="/detail{{good.id}}/"><img src="/static/{{good.gpic}}"></a>
						<h4><a href="/detail{{good.id}}/">{{good.gtitle}}</a></h4>
						<div class="operate">
							<span class="prize">￥{{good.gprice}}</span>
							<span class="unit">{{good.gprice}}/{{good.gunit}}</span>
							<a href="#" class="add_goods" title="加入购物车"></a>
						</div>
						</li>
					{%endfor%}

			</ul>
			</div>
		</div>
	</div>
{%endblock content%}



project/templates/appname1/user_center_order.html
{%extends 'appname1/base_temp.html'%}
{%block head%}
<script>
	$(function () {
		$('.col04').each(function () {
			var count = parseInt($(this).prev().text());
			var price = parseFloat($(this).prev().prev().find('span').text());
			var totle = count*price;
			$(this).text(totle.toFixed(2));
        })
    })
</script>
{%endblock head%}
{%block user%}
{{block.super}}
{%endblock user%}
{%block content%}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user_center_info/">· 个人信息</a></li>
				<li><a href="/user_center_order/" class="active">· 全部订单</a></li>
				<li><a href="/user_center_site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				{%for order in page%}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{order.order_date}}</li>
					<li class="col02">订单号：{{order.order_id}}</li>
					<li class="col02 stress">{%if order.state == 1%}已支付{%else%}未支付{%endif%}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								{%for detail in order.orderdetail_set.all%}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/{{detail.goods.gpic}}"></li>
									<li class="col02">{{detail.goods.gtitle|truncatechars:15}}<em><span>{{detail.goods.gprice}}</span>/{{detail.goods.gunit}}</em></li>
									<li class="col03">{{detail.count}}</li>
									<li class="col04">11.80元</li>	
								</ul>
								{%endfor%}
							</td>
							<td width="15%">{{order.total}}元</td>

							{%if order.state == 1%}
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
							{%else%}
							<td width="15%">待付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
							{%endif%}

						</tr>
					</tbody>
				</table>
				{%endfor%}


				<div class="pagenation">

					{%if page.has_previous%}
					<a href="/user_center_order/"><首页</a>
					<a href="/user_center_order/?index={{page.number|add:-1}}"><上一页</a>
					{%endif%}
					{%for index in pagenum%}
					{%if index == page.number%}
					<a href="#" class="active">{{index}}</a>
					{%else%}
					<a href="/user_center_order/?index={{index}}">{{index}}</a>
					{%endif%}
					{%endfor%}
					{% if page.has_next %}
					<a href="/user_center_order/?index={{page.number|add:1}}">下一页></a>
					<a href="/user_center_order/?index={{page.paginator.num_pages}}">尾页></a>
					{%endif%}
				</div>
		</div>
	</div>
{%endblock content%}



project/templates/appname1/user_center_site.html
{%extends 'appname1/base_temp.html'%}
{%block user%}
{{block.super}}
{%endblock user%}
{%block content%}
		<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user_center_info/">· 个人信息</a></li>
				<li><a href="/user_center_order/">· 全部订单</a></li>
				<li><a href="/user_center_site/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						{#<dd>北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528</dd>#}
						{%if user.uaddress == None%}
						<dd>无收件信息</dd>
						{%else%}
						<dd>{{user.uaddress|default:''}} （{{user.ureceive|default:''}}收） {{user.uphone|default:''}}</dd>
						{%endif%}
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post" action="/userinfo_handle/">
						{%csrf_token%}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ureceive">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="address"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{%endblock content%}